# Generated by Django 6.0.6 on 2026-07-31 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matric_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff_id',
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=30, unique=True)),
                ('office', models.CharField(blank=True, max_length=200)),
                ('rank', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('employment_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='lecturers/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(max_length=30, unique=True)),
                ('admission_number', models.CharField(max_length=30, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(default='Nigeria', max_length=100)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('admission_date', models.DateField()),
                ('passport', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deferred', 'Deferred'), ('Graduated', 'Graduated'), ('Suspended', 'Suspended'), ('Withdrawn', 'Withdrawn')], default='Active', max_length=20)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.level')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.programme')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicsession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
